### ISSUE TITLE
Remaining Backend Issues list in order of priority (12/9/2019)

### ISSUE THREAD

**Issue by mfogel** [real-social-media/backend#10]
- [ ] Video Post Support #3

- [ ] Apple Pay + is_diamond user property. This should be set to true when a webhook comes from Apple Pay, saying the user made a payment. #4

- [ ] Check UnSubscriptions (Routine): This should be a routine which runs once per day, and calls an Apple Pay API to get a list of all subscribers which is crossed referenced by query in our database for all users where (is_diamond == true). If any users have (is_diamond == true), but are not present in the apple pay subscribers payload, set the users (is_diamond = false), removing his membership. This should run once per day or less. It is a routine for garbage collection. #4

- [ ] Mental health setting to limit posts seen over the past 24 hours #6

- [ ] Error codes #7

- [ ] Diamond Members Get Paid Per View From Other Diamond Members #4

- [ ] loading icon added to generated thumbnails

- [ ] Load Testing 10,000 user simulation #8

- [ ] Auto detect inappropriate content : If > 20 % of the people who view a post report/flag it, and total views is > 20, archive the post.

- [ ] Load Testing 100,000 user simulation #8

- [ ] Update post verification to support videos. Video posts should pass verification when their filesize is >= (video_length_in_seconds * 0.2)MB. Images should continue to pass verification if their filesize is >= 1MB. Both of these should be variables which are easy to change in the future as our perception/standards for high quality changes.

- [ ] Encoding & storing thumbnail, 480, 720, 1080p, native formats of video uploads.

- [ ] Implement allowing the users to transfer their REAL account balance to their PayPal/Braintree account via the PayPal payouts https://developer.paypal.com/docs/payouts/
